### ISSUE TITLE
No Proper Component Channels [HIGH PRIORITY]

### ISSUE THREAD

**Issue by atomicdiamond** [CircuitOfLifeRobotics/Robot2016-Limbot#1]
**HIGH PRIORITY ISSUE**

None of the Talons, encoders, or CANTalonSRX's have actual channels!
Get electrical team to generate and give you a wiring diagram.

**Comment by CubeMaster007** [comment]
This isn't a bug. But ok. Will do tonight

**Comment by atomicdiamond** [comment]
Most of ports are done. Closing issue.
