### ISSUE TITLE
Launcher Shooter Wheels PID Not Working

### ISSUE THREAD

**Issue by CubeMaster007** [CircuitOfLifeRobotics/Robot2016-Limbot#3]
Using velocity PID on the shooter wheels of the bot, the right wheel spins to the correct RPM, but the left wheel seems to be set to position mode.

**Comment by atomicdiamond** [comment]
We will not be implementing this. Launcher wheel speeds are similar enough at full battery and low battery for it not to matter. It is also more tuning that will have to be done on practice day.
